spellbook/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.SpellList.as_view(), name='home'),
    path('spell/<int:id>/', views.spell_detail, name='spell_detail'),
    path('spell/create', views.spell_create, name='spell_create'),
    path('spell/edit/<int:id>/', views.spell_edit, name='spell_edit'),
    path('spell/delete/<int:id>/', views.spell_delete, name='spell_delete'),
    path('about', views.spell_about, name='spell_about')
]

spellsmith/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include("spellbook.urls"), name='spellbook_urls'),
]

spellbook/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

SCHOOL = ((0, "Astromancy"), (1, "Chronomancy"), (2, "Conjuration"),
          (3, "Destruction"), (4, "Divination"), (5, "Enchantment"),
          (6, "Illusion"), (7, "Necromancy"), (8, "Protection"),
          (9, "Restoration"), (10, "Transmutation"))


# Models
class Spell(models.Model):
    creator = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="homebrew_spell_entries")
    name = models.CharField(max_length=256)
    excerpt = models.TextField(blank=True, max_length=256)
    school = models.IntegerField(choices=SCHOOL, default=0)
    ap_cost = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(4)])
    mp_cost = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(9)])
    range = models.CharField(max_length=256)
    duration = models.CharField(max_length=256)
    concentration = models.BooleanField()
    description = models.TextField(unique=True)
    ap_enhancements = models.TextField(blank=True)
    mp_enhancements = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"{self.name} | written by {self.creator}"

spellbook/forms.py
from .models import Spell
from django import forms


class SpellForm(forms.ModelForm):
    class Meta:
        model = Spell
        fields = ['name', 'excerpt', 'school', 'ap_cost', 'mp_cost', 'range',
                  'duration', 'concentration', 'description', 'description',
                  'ap_enhancements', 'mp_enhancements']

        # This adds form validation feedback on submit
        widgets = {
            'ap_cost': forms.NumberInput(attrs={'min':1, 'max':4}),
            'mp_cost': forms.NumberInput(attrs={'min':0, 'max':10})
        }

spellbook/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from django.views import generic
from django.contrib import messages
from django.urls import reverse
from .models import Spell
from .forms import SpellForm


# Homepage
# Uses Django Generic list view
class SpellList(generic.ListView):
    model = Spell
    template_name = "spellbook/spell_list.html"
    paginate_by = 12


# Detail Page
# It is passed the detail of a spell a displays it in a format that matches a
# DC20 spell template
def spell_detail(request, id):
    """
    Display an individual spell.

    **Context**

    ``spell``
        An instance of a spell model.

    **Template:**

    :template:`spellbook/spell_detail.html`
    """

    queryset = Spell.objects.all()
    spell = get_object_or_404(queryset, id=id)

    return render(
        request,
        "spellbook/spell_detail.html",
        {"spell": spell},
    )


# Create Page
# A page that uses a Crispy Form to take a new spell and POST it to the
# database
def spell_create(request):
    """
    A function that displays the spell_create
    """
    spell_form = SpellForm()

    if request.method == "POST":
        spell_form = SpellForm(data=request.POST)
        if spell_form.is_valid():
            spell = spell_form.save(commit=False)
            spell.creator = request.user
            spell.save()

            messages.add_message(
                request, messages.SUCCESS,
                'Your spell has been scribed into the communual spellbook!'
            )
            id = spell.id
            return HttpResponseRedirect(reverse('spell_detail',
                                                kwargs={'id': id}))
        else:
            messages.add_message(
                request, messages.Error,
                'Error creating a spell, Please create a bug report <a href="https://github.com/LaurieAnderson92/Spellsmith/issues/new?assignees=&labels=&projects=&template=bug_report.md&title="> here </a>'
            )
    return render(
        request,
        "spellbook/spell_create.html",
        {"spell_form": spell_form}
            )


def spell_edit(request, id):
    """
    View to edit spells
    """
    spell = get_object_or_404(Spell, pk=id)
    if request.user == spell.creator:
        if request.method == "POST":
            spell_form = SpellForm(data=request.POST, instance=spell)
            if spell_form.is_valid():
                spell.save()
                return HttpResponseRedirect(reverse('spell_detail',
                                                    kwargs={'id': id}))
        spell_form = SpellForm(instance=spell)

        return render(
            request,
            "spellbook/spell_create.html",
            {"spell_form": spell_form}
        )
    messages.add_message(
                request, messages.WARNING,
                'You do not have permission to edit this spell'
            )
    return HttpResponseRedirect(reverse('home'))


def spell_delete(request, id):
    """
    view to delete spells
    """
    spell = get_object_or_404(Spell, pk=id)

    if spell.creator == request.user:
        spell.delete()
        messages.add_message(
                request, messages.SUCCESS,
                'The spell has been successfully removed'
            )
        return redirect('home')

    else:
        messages.add_message(
            request, messages.WARNING,
            'You do not have permission to delete this spell'
            )
        return redirect('home')


def spell_about(request):
    """
    View for the About Page
    """
    return render(request, "spellbook/spell_about.html",)

spellbook/templates/spellbook/spell_about.html
{% extends 'base.html' %} {% block content %}
{% load static %}

<div class="container">
    <div class="row mb-4">
        <div class="card-body">
            <h1>About Spellsmith</h1>

            <p>Welcome to Spellsmith, a community-driven platform dedicated to exploring and expanding the magic of the upcoming DC20 
                Roleplaying System by Dungeon Coach. This website is a fan-built initiative designed to serve as a hub for homebrew 
                spells, giving players and Game Masters alike a place to discover, share, and enhance their gameplay experience.</p>

            <p>At Spellsmith, we aim to bring creativity and collaboration to the forefront. Our growing collection of homebrew spells
                is contributed by passionate members of the DC20 community. Whether you're looking for unique elemental attacks, 
                creative utility spells, or game-changing enchantments, you'll find a wide range of magical possibilities here, 
                all tailored to fit DC20's dynamic mechanics.</p>

            <p>This site isn't just about offering pre-made content—it's about fostering a community of creators who are eager to push 
                the boundaries of the DC20 magic system. Whether you're a seasoned spell crafter or just getting started, we encourage 
                you to contribute your own ideas, test out new spells in your campaigns, and engage with fellow fans to help build the 
                future of DC20 magic.</p>

            <p>So explore, experiment, and expand your spellbook with us. Together, we can forge new realms of magical potential for 
                the DC20 universe!</p>
        </div>
    </div>
</div>


{% endblock content %}

spellbook/templates/spellbook/spell_create.html
{% extends 'base.html' %} {% block content %}
{% load static %}
{% load crispy_forms_tags %}

<!-- This DTL displays the form that is used to create a spell, 
 the form itself posts the result to the databse on submit.
 form validation controls are done at spellbook/forms.py -->
<div class="container">
  <div class="row mb-4">
    <div class="card-body">
      <h1 class= "text-center p-3">Create A Spell</h1>
      <form id="spellForm" method="post">
        {{ spell_form.name | as_crispy_field}}
        {{ spell_form.excerpt | as_crispy_field}}
        <div class="row justify-content-center">
          <div class = "col-md-4">
            {{ spell_form.school | as_crispy_field}}
          </div>
          <div class = "col-md-4">
            {{ spell_form.ap_cost | as_crispy_field}}
          </div>
          <div class = "col-md-4">
            {{ spell_form.mp_cost | as_crispy_field}}
          </div>
        </div>
        <div class="row justify-content-center">
          <div class = "col-md-4">
            {{ spell_form.range | as_crispy_field}}
          </div>
          <div class = "col-md-4">
            {{ spell_form.duration | as_crispy_field}}
          </div>
          <div class = "col-md-4 pt-md-4 mt-md-3 ">
            {{ spell_form.concentration | as_crispy_field}}
          </div>
        </div>
        {{ spell_form.description | as_crispy_field}}
        {{ spell_form.ap_enhancements | as_crispy_field}}
        {{ spell_form.mp_enhancements | as_crispy_field}}
        {% csrf_token %}
        <button id="submitButton" type="submit"
                class="btn btn-success btn-lg">Submit</button>
      </form>
    </div>
  </div>
</div>  
  {% endblock content %}

spellbook/templates/spellbook/spell_detail.html
{% extends 'base.html' %} {% block content %}
{% load static %}

<!-- This DTL displays the full details of the spell correlating to the integer it was passed -->
<div class="container">
    <div class="row">
      <div class="card-body">
              <h1 class="post-title">{{ spell.name }}</h1>
                <p class="post-subtitle">{{ spell.get_school_display }} {% if spell.mp_cost == 0 %} (Cantrip) {% endif %}</p>
                <p class="card-text">
                    <strong>Cost:</strong> {{spell.ap_cost}} AP {% if spell.mp_cost != 0 %} + {{spell.mp_cost}} MP {% endif %}
                    <br>
                    <strong>Range:</strong>  {{spell.range}} 
                    <br>
                    <strong>Duration:</strong> {{spell.duration}} {% if spell.concentration == True %} <strong>(concentration)</strong> {% endif %}
                    <br>
                    {{ spell.description | safe }}
                    <br>
                    {% if spell.ap_enhancements %}
                        <br>
                        <strong>AP Enhancements:</strong>
                        <br>
                        {{ spell.ap_enhancements | safe  }}
                    {% endif %}
                    {% if spell.mp_enhancements %}
                    <br>
                        <strong>MP Enhancements:</strong>
                        <br>
                        {{ spell.mp_enhancements | safe  }}
                    {% endif %}
                </p>
            <p class="pt-3"><em>{{ spell.excerpt | safe }}</em></p>
        </div>
        <p>{{ spell.creator }} | {{ spell.created_on }}</p>
        {% if user.is_authenticated and spell.creator == user %}
        <div class="row">
          <div class="col-4 p-3"><a href="{% url 'spell_edit' spell.id %}" class="btn btn-secondary">Edit</a></div>
          <div class="col-4 p-3"><button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal">Delete</button></div>
        </div>
        {% endif %}
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Warning: Deleting a spell is permanent</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        By clicking delete again, you confirm that you are deleting this spell for the community and understand that it cannot be recovered.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a href="{% url 'spell_delete' spell.id %}" class="btn btn-danger">Delete</a>
        
      </div>
    </div>
  </div>
</div>
{% endblock content %}

spellbook/templates/spellbook/spell_list.html
{% extends "base.html" %}
{% block content %}
<div class="row">
  <!-- This DTL iterates through the spell model and displays the spells -->
{% for spell in spell_list %}
    <div class="col-md-4">
        <div class="card mb-4">
            <div class="card-body">
                <a href="{% url 'spell_detail' spell.id %}">
                <h2 class="card-title">{{ spell.name }}</h2>
                <p class="card-text h6">{{ spell.get_school_display }}</p>
                <hr>
                <p class="card-text">{{ spell.excerpt }}</p>
                </a>
            </div>
        </div>
    </div>
{% endfor %}
</div>
<!-- Pagnation code, taken from Code|star project -->
<!-- This code creates the ability to cycle through the pages if the number is spells is 
greater than the value set in the SpellList View -->
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
  {% endif %}
  </ul>
</nav>
{% endif %}

{% endblock %}

templates/base.html
{% url 'home' as home_url%}

{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>SpellSmith</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Google Fonts CSS -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Merienda:wght@300..900&display=swap" rel="stylesheet">

    <!-- Font Awesome CSS -->
    <script src="https://kit.fontawesome.com/38fef1e39a.js" crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    
    <!-- Project CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <!-- Favicon -->
    <link rel="icon" href="{% static 'images/favicon/favicon.ico' %}">
</head>
<body>
  <!-- Navigation Bar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}"><span class="purple">Spell</span>Smith</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Spellbook</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'spell_about' %}">About</a>
          </li>
          <!-- This DTL checks if the user is logged in and if so, displays the link to create a spell 
          and the logout Url, otherwise is shows the Sign up / Login Links -->
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'spell_create' %}">Create a Spell</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == logout_url %}active{% endif %}"
              href="{% url 'account_logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link {% if request.path == signup_url %}active{% endif %}"
              href="{% url 'account_signup' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == login_url %}active{% endif %}"
              href="{% url 'account_login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Alert Box -->
  <div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
          <!-- This DTL Cycles through messages and displays them using Bootstraps5 -->
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible
              fade show" id="msg" role="alert">
              {{ message | safe }}
              <button type="button" class="btn-close"
                data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
  <main>
    <div class="container min-vh-100">
      {% block content %}

      {% endblock content %}
    </div>
  </main>
  <!-- Footer -->
  <footer class="py-3 bg-dark" >   
    <div class="container-fluid">
      <p class="text-light">© 2024 Copyright| Fullstack Anderson</p>
      <p class="m-0 text-center text-light">Check out the Dungeon Coach | 
        <a href="https://discord.gg/thedungeoncoach" target="_blank" rel="noopener" aria-label="visit the Discord server (opens in a new tab)">
          <i class="fa-brands fa-discord text-light"></i>
        </a>
        <a href="https://www.youtube.com/@TheDungeonCoach" target="_blank" rel="noopener" aria-label="visit the Youtube Channel (opens in a new tab)">
        <i class="fa-brands fa-youtube text-light"></i>
        </a>
      </p>
      <p class="m-0 text-center text-light">Help out with the project |  
        <a href="https://github.com/LaurieAnderson92/Spellsmith" target="_blank" rel="noopener" aria-label="visit the Github Repository (opens in a new tab)">
          <i class="fa-brands fa-github text-light"></i>
        </a>
      </p>
    </div>
  </footer>
  <!-- Bootstrap JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
</script>
</body>
</html>

templates/mfa/authenticate.html
{% extends "mfa/base_entrance.html" %}
{% load i18n %}
{% load allauth %}
{% load allauth static %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        {% trans "Two-Factor Authentication" %}
    {% endelement %}
    {% element p %}
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    {% endelement %}
    {% url 'mfa_authenticate' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form unlabeled=True %}
            {% endelement %}
        {% endslot %}
        {% slot actions %}
            {% element button type="submit" tags="primary,mfa,login" %}
                {% trans "Sign In" %}
            {% endelement %}
            {% if "webauthn" not in MFA_SUPPORTED_TYPES %}
                {% element button type="submit" form="logout-from-stage" tags="link,mfa,cancel" %}
                    {% trans "Cancel" %}
                {% endelement %}
            {% endif %}
        {% endslot %}
    {% endelement %}
    {% if "webauthn" in MFA_SUPPORTED_TYPES %}
        {% element hr %}
        {% endelement %}
        {% element h2 %}
            {% translate "Alternative options" %}
        {% endelement %}
        {% element button_group vertical=True %}
            {% element button form="webauthn_form" id="mfa_webauthn_authenticate" type="button" tags="outline,primary" %}
                {% trans "Use a security key" %}
            {% endelement %}
            {% element button type="submit" form="logout-from-stage" tags="outline,primary,mfa,cancel" %}
                {% trans "Cancel" %}
            {% endelement %}
        {% endelement %}
        {% if "webauthn" in MFA_SUPPORTED_TYPES %}
            {% element form id="webauthn_form" form=webauthn_form method="post" action=action_url no_visible_fields=True %}
                {% slot body %}
                    {% csrf_token %}
                    {% element fields form=webauthn_form %}
                    {% endelement %}
                {% endslot %}
            {% endelement %}
            {{ js_data|json_script:"js_data" }}
            {% include "mfa/webauthn/snippets/scripts.html" %}
            <script>
        allauth.webauthn.forms.authenticateForm({
        ids: {
        authenticate: "mfa_webauthn_authenticate",
        credential: "{{ webauthn_form.credential.auto_id }}"
        },
        data: JSON.parse(document.getElementById('js_data').textContent)
        })
            </script>
        {% endif %}
    {% endif %}
    <form id="logout-from-stage"
          method="post"
          action="{% url 'account_logout' %}">
        <input type="hidden" name="next" value="{% url 'account_login' %}">
        {% csrf_token %}
    </form>
{% endblock content %}

templates/mfa/base_entrance.html
{% extends "allauth/layouts/entrance.html" %}

templates/mfa/base_manage.html
{% extends "allauth/layouts/manage.html" %}

templates/mfa/index.html
{% extends "mfa/base_manage.html" %}
{% load allauth %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    {% element h1 tags="mfa,index" %}
        {% trans "Two-Factor Authentication" %}
    {% endelement %}
    {% if "totp" in MFA_SUPPORTED_TYPES %}
        {% element panel %}
            {% slot title %}
                {% translate "Authenticator App" %}
            {% endslot %}
            {% slot body %}
                {% if authenticators.totp %}
                    {% element p %}
                        {% translate "Authentication using an authenticator app is active." %}
                    {% endelement %}
                {% else %}
                    {% element p %}
                        {% translate "An authenticator app is not active." %}
                    {% endelement %}
                {% endif %}
            {% endslot %}
            {% slot actions %}
                {% url 'mfa_deactivate_totp' as deactivate_url %}
                {% url 'mfa_activate_totp' as activate_url %}
                {% if authenticators.totp %}
                    {% element button href=deactivate_url tags="danger,delete,panel" %}
                        {% translate "Deactivate" %}
                    {% endelement %}
                {% else %}
                    {% element button href=activate_url tags="panel" %}
                        {% translate "Activate" %}
                    {% endelement %}
                {% endif %}
            {% endslot %}
        {% endelement %}
    {% endif %}
    {% if "webauthn" in MFA_SUPPORTED_TYPES %}
        {% element panel %}
            {% slot title %}
                {% translate "Security Keys" %}
            {% endslot %}
            {% slot body %}
                {% if authenticators.webauthn|length %}
                    {% element p %}
                        {% blocktranslate count count=authenticators.webauthn|length %}You have added {{ count }} security key.{% plural %}You have added {{ count }} security keys.{% endblocktranslate %}
                    {% endelement %}
                {% else %}
                    {% element p %}
                        {% translate "No security keys have been added." %}
                    {% endelement %}
                {% endif %}
            {% endslot %}
            {% slot actions %}
                {% if authenticators.webauthn|length %}
                    {% url 'mfa_list_webauthn' as webauthn_list_url %}
                    {% element button href=webauthn_list_url %}
                        {% translate "Manage" %}
                    {% endelement %}
                {% else %}
                    {% url 'mfa_add_webauthn' as webauthn_add_url %}
                    {% element button href=webauthn_add_url %}
                        {% translate "Add" %}
                    {% endelement %}
                {% endif %}
            {% endslot %}
        {% endelement %}
    {% endif %}
    {% if "recovery_codes" in MFA_SUPPORTED_TYPES %}
        {% with total_count=authenticators.recovery_codes.generate_codes|length unused_count=authenticators.recovery_codes.get_unused_codes|length %}
            {% element panel %}
                {% slot title %}
                    {% translate "Recovery Codes" %}
                {% endslot %}
                {% slot body %}
                    {% if authenticators.recovery_codes %}
                        {% element p %}
                            {% blocktranslate count unused_count=unused_count %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
                        {% endelement %}
                    {% else %}
                        {% element p %}
                            {% translate "No recovery codes set up." %}
                        {% endelement %}
                    {% endif %}
                {% endslot %}
                {% if is_mfa_enabled %}
                    {% if authenticators.recovery_codes %}
                        {% if unused_count > 0 %}
                            {% slot actions %}
                                {% url 'mfa_view_recovery_codes' as view_url %}
                                {% element button href=view_url tags="panel" %}
                                    {% translate "View" %}
                                {% endelement %}
                            {% endslot %}
                            {% slot actions %}
                                {% url 'mfa_download_recovery_codes' as download_url %}
                                {% element button href=download_url tags="secondary,panel" %}
                                    {% translate "Download" %}
                                {% endelement %}
                            {% endslot %}
                        {% endif %}
                    {% endif %}
                    {% slot actions %}
                        {% url 'mfa_generate_recovery_codes' as generate_url %}
                        {% element button href=generate_url tags="secondary,panel" %}
                            {% translate "Generate" %}
                        {% endelement %}
                    {% endslot %}
                {% endif %}
            {% endelement %}
        {% endwith %}
    {% endif %}
{% endblock content %}

templates/mfa/reauthenticate.html
{% extends "account/base_reauthenticate.html" %}
{% load i18n %}
{% load allauth %}
{% block reauthenticate_content %}
    {% element p %}
        {% blocktranslate %}Enter an authenticator code:{% endblocktranslate %}
    {% endelement %}
    {% url 'mfa_reauthenticate' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form unlabeled=True %}
            {% endelement %}
            {{ redirect_field }}
        {% endslot %}
        {% slot actions %}
            {% element button type="submit" tags="primary,mfa,login" %}
                {% trans "Confirm" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock %}

templates/mfa/recovery_codes/base.html
{% extends "mfa/base_manage.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% load allauth %}
{% block content %}
    {% element h1 %}
        {% translate "Recovery Codes" %}
    {% endelement %}
    {% element p %}
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account.{% endblocktranslate %}
        {% if unused_code_count %}
            {% blocktranslate %}This action will invalidate your existing codes.{% endblocktranslate %}
        {% endif %}
        {% blocktranslate %}Are you sure?{% endblocktranslate %}
    {% endelement %}
    {% url 'mfa_generate_recovery_codes' as action_url %}
    {% element form method="post" action=action_url no_visible_fields=True %}
        {% slot body %}
            {% csrf_token %}
            {{ form.as_p }}
        {% endslot %}
        {% slot actions %}
            {% setvar tags %}
                {% if unused_code_count %}
                    danger
                {% else %}
                {% endif %}
            {% endsetvar %}
            {% element button type="submit" tags=tags %}
                {% trans "Generate" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/mfa/totp/base.html
{% extends "mfa/base_manage.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/mfa/webauthn/base.html
{% extends "mfa/base_manage.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Security Keys" %}
{% endblock head_title %}

templates/mfa/webauthn/snippets/scripts.html
{% load i18n static %}
<noscript>{% translate "This functionality requires JavaScript." %}"</noscript>
<script src="{% static 'mfa/js/webauthn-json.js' %}"></script>
<script src="{% static 'mfa/js/webauthn.js' %}"></script>